import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: {  children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-darkest text-primary`}>
        <main className="flex items-center justify-center px-8 h-dvh">
          {children}
        </main>
      </body>
    </html>
  )
}
